-- Generated by Monique - https://github.com/ToRvaLDz/monique

hl.monitor({
  output = "desc:Hewlett Packard HP 2211 CNK2220CM0",
  disabled = true,
})

hl.monitor({
  output = "desc:AOC Q25G4S XL2RAHA000422",
  mode = "2560x1440@60",
  position = "1600x0",
  scale = 1.6,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:BNQ BenQ PD2500Q F7L0400601Q",
  mode = "2560x1440@59.951",
  position = "0x0",
  scale = 1.6,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.config({
  cursor = { default_monitor = "desc:BNQ BenQ PD2500Q F7L0400601Q" },
})

hl.workspace_rule({ workspace = "1", monitor = "desc:BNQ BenQ PD2500Q F7L0400601Q", persistent = true, })
hl.workspace_rule({ workspace = "2", monitor = "desc:BNQ BenQ PD2500Q F7L0400601Q", persistent = true, })
hl.workspace_rule({ workspace = "3", monitor = "desc:BNQ BenQ PD2500Q F7L0400601Q", persistent = true, })
hl.workspace_rule({ workspace = "4", monitor = "desc:BNQ BenQ PD2500Q F7L0400601Q", persistent = true, })
hl.workspace_rule({ workspace = "5", monitor = "desc:BNQ BenQ PD2500Q F7L0400601Q", persistent = true, })
hl.workspace_rule({ workspace = "6", monitor = "desc:AOC Q25G4S XL2RAHA000422", persistent = true, })
hl.workspace_rule({ workspace = "7", monitor = "desc:AOC Q25G4S XL2RAHA000422", persistent = true, })
hl.workspace_rule({ workspace = "8", monitor = "desc:AOC Q25G4S XL2RAHA000422", persistent = true, })
hl.workspace_rule({ workspace = "9", monitor = "desc:AOC Q25G4S XL2RAHA000422", persistent = true, })
hl.workspace_rule({ workspace = "0", persistent = true, })
